[mypy]
python_version = 3.11
strict = True
check_untyped_defs = True
warn_return_any = True
warn_unused_configs = True
mypy_path = src

[mypy-md2pdf]
ignore_missing_imports = True

[mypy-mermaid]
ignore_missing_imports = True

[mypy-markdown2]
ignore_missing_imports = True

[mypy-tqdm]
ignore_missing_imports = True
